CREATE TABLE "dm_municipality" (
  "municipality_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(10) UNIQUE NOT NULL,
  "name" varchar(150) NOT NULL,
  "province" varchar(100),
  "region" varchar(100),
  "latitude" real,
  "longitude" real
);

CREATE TABLE "dm_axis" (
  "axis_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150) UNIQUE NOT NULL
);

CREATE TABLE "dm_service" (
  "service_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "axis_id" int NOT NULL,
  "name" varchar(200) NOT NULL,
  "service_code" varchar(20) UNIQUE NOT NULL,
  "grouping" varchar(50),
  "diversified_key" varchar(50),
  UNIQUE ("axis_id", "name")
);

CREATE TABLE "dm_municipality_diversified_service" (
  "municipality_id" int NOT NULL,
  "service_id" int NOT NULL,
  PRIMARY KEY ("municipality_id", "service_id")
);

CREATE TABLE "dm_stage" (
  "stage_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "dm_indicator" (
  "indicator_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "service_id" int NOT NULL,
  "stage_id" int NOT NULL,
  "code" varchar(30) UNIQUE NOT NULL,
  "name" varchar(300) NOT NULL,
  "type" varchar(50),
  "evidence_required" boolean,
  "documentation" varchar(300)
);

CREATE TABLE "fact_indicator_response" (
  "response_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date_time" datetime NOT NULL,
  "municipality_id" int NOT NULL,
  "indicator_id" int NOT NULL,
  "value" real NOT NULL,
  UNIQUE ("municipality_id", "indicator_id", "value")
);

CREATE TABLE "fact_stage_weight" (
  "stage_weight_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "planning_weight" real NOT NULL,
  "execution_weight" real NOT NULL,
  "evaluation_weight" real NOT NULL,
  "effective_from" date NOT NULL
);

CREATE TABLE "fact_maturity_threshold" (
  "threshold_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "initial_upper" real NOT NULL,
  "basic_upper" real NOT NULL,
  "intermediate_upper" real NOT NULL,
  "advanced_upper" real NOT NULL,
  "optimizing_upper" real NOT NULL,
  "effective_from" date NOT NULL
);

CREATE INDEX ON "fact_indicator_response" ("municipality_id", "indicator_id", "date_time");

CREATE INDEX ON "fact_indicator_response" ("date_time");

ALTER TABLE "dm_service" ADD FOREIGN KEY ("axis_id") REFERENCES "dm_axis" ("axis_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "dm_municipality_diversified_service" ADD FOREIGN KEY ("municipality_id") REFERENCES "dm_municipality" ("municipality_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "dm_municipality_diversified_service" ADD FOREIGN KEY ("service_id") REFERENCES "dm_service" ("service_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "dm_indicator" ADD FOREIGN KEY ("service_id") REFERENCES "dm_service" ("service_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "dm_indicator" ADD FOREIGN KEY ("stage_id") REFERENCES "dm_stage" ("stage_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "fact_indicator_response" ADD FOREIGN KEY ("municipality_id") REFERENCES "dm_municipality" ("municipality_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "fact_indicator_response" ADD FOREIGN KEY ("indicator_id") REFERENCES "dm_indicator" ("indicator_id") DEFERRABLE INITIALLY IMMEDIATE;
